### ISSUE TITLE
Provide a dist version for use in Webpack

### ISSUE THREAD

**Issue by TimonVS** [angeloashmore/ics-js#13]
Webpack can't handle ES6 imports right now (without using Babel for node_modules). So providing a dist version would be great.

**Comment by angeloashmore** [comment]
Sure, I should have time today to implement this.

**Comment by angeloashmore** [comment]
Fixed and published to NPM with https://github.com/angeloashmore/ics-js/commit/de52e672337968ee579f7ba83acf69c2d64fe2f9. Please let me know if you run into issues using the dist version.

Thanks!

**Comment by Artemidas** [comment]
Just tried dist version of an ics-js and got following error:
`ERROR in app/js/main.js from UglifyJs`
`Unexpected token: name (ParseIt) [./~/ics-js/dist/ics-js.js:1971,0]`

**Comment by angeloashmore** [comment]
I believe this is an error due to the `parse-it` package not being transpiled to ES5. This can temporarily be fixed by having babel transpile the whole `ics-js` package a second time.

I'm working on improving documentation and cleaning up some of the code. Part of that will be removing the formatoid/format-date dependency.

I will publish a new version shortly that fixes the error.

**Comment by angeloashmore** [comment]
Fixed and published.
