### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by didymu5** [angeloashmore/ics-js#17]
I was following the usage:
` 
const cal = new ICS.VCALENDAR();
`
And I was getting this error:
```
const cal = new ICS.VCALENDAR();
            ^

TypeError: ICS.VCALENDAR is not a function
```
But when I do
`const cal = new ICS.default.VCALENDAR();' then it seems to work. I'm not sure if that's how you intended for people to use this.

**Comment by angeloashmore** [comment]
I'm having some trouble getting the webpack config to do what I want it to do.

I set the target to `node` and the libraryTarget to `umd`, but it isn't exporting the modules properly. Any chance you know a fix?

**Comment by angeloashmore** [comment]
Turns out I was incorrectly exporting the modules. Babel 6 treats default exports differently than Babel 5 and this library was not updated to support it.

https://github.com/angeloashmore/ics-js/commit/cacf992243232fc92c940ed4df090bf3b1586418 fixes this issue.

ics-js 0.8.10 is published and should be working. Please reopen if you still get this issue.

Thanks!

**Comment by angeloashmore** [comment]
`0.9.0` has been published with a slightly different API.

When importing the library, the following methods can be used:

**Import all components under `ICS`** (e.g. `ICS.VCALENDAR`, `ICS.VEVENT`):
```js
import * as ICS from 'ics-js';
```

**Import components explicitly** (e.g. `VCALENDAR`, `VEVENT`):
```js
import { VCALENDAR, VEVENT } from 'ics-js';
```

### Important

_The previous method of importing the library is now unsupported_:
```js
import ICS from 'ics-js';
```
