### ISSUE TITLE
toBlob# and toBase64# fails on node.js

### ISSUE THREAD

**Issue by EivindEE** [angeloashmore/ics-js#20]
`toBlob#` calls `new Blob#` which is unavailable on node.js. This causes these two functions to fail.

**Comment by angeloashmore** [comment]
`#toBlob` is a browser-only function since, as you noted, `Blob` does not exist in Node.js. Rather than trying to implement a special case, like creating a buffer if `Blob` is not detected, it might be better to note this in the docs and alert the user as an error (via `console.error()`?).

`#toBase64`, however, should definitely be implemented for Node.js. I'll take some time later to implement this. Or if you have some time to submit a PR, the help is welcomed. 😄

**Comment by angeloashmore** [comment]
[v0.10.0](https://github.com/angeloashmore/ics-js/releases/tag/v0.10.0) published to NPM. Thanks again! 👍
